export const brandOption=[
    {
        brandname:"Samsung",
        price:45
    },
    {
        brandname:"Apple",
        price:21
    },
    {
        brandname:"Oppo",
        price:70
    },
    {
        brandname:"Vivo",
        price:56
    },
    {
        brandname:"Mi",
        price:23
    },
    {
        brandname:"Oneplus",
        price:26
    },
    {
        brandname:"Lava",
        price:15
    },
]