import phone2 from "../../common/asset/product-2.svg"
import phone3 from "../../common/asset/product-3.svg"
import phone4 from "../../common/asset/product-4.svg";

export const  phoneProducts=[{
    cashback:"12% Cashback",
    phoneName: "Samsung Galaxy S10 Plus",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    imageArray:[phone2,phone3,phone4],
    brand: "Samsung",
    id:"1533",
},
{
   
    cashback:"15% Cashback",
    phoneName: "Iphone 15 256 GB Pink color",
    currentPrice:"Rs.58,354",
    discountPrice:"Rs.65,9999",
    discount:"1% off",
    phoneEmi:"EMI starts @ Rs4556",
    availableColors: ["red", "blue"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    imageArray:[phone4,phone3,phone2],
    brand: "Iphone",
    id:"15335",
},
{

    cashback:"12% Cashback",
    phoneName: "Vivo 12 with 32 px front camera",
    currentPrice:"Rs.30,000",
    discountPrice:"Rs.35,9999",
    discount:"10% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Vivo",
    imageArray:[phone3,phone2,phone4],
    id:"15233",
},
{
    cashback:"12% Cashback",
    phoneName: "One Plus balck body with 64GB",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Oneplus",
    imageArray:[phone4,phone3,phone2],
    id:"1535553",
},
{
    cashback:"12% Cashback",
    phoneName: "Samsung Galaxy S10 Plus",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue",  "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Samsung",
    imageArray:[phone2,phone3,phone4],
    id:"15123133",
},
{
    cashback:"12% Cashback",
    phoneName: "Iphone 15 256 GB Pink color",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Iphone",
    imageArray:[phone2,phone3,phone4],
    id:"153378",
},
{
    cashback:"12% Cashback",
    phoneName: "Vivo 12 with 32 px front camera",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Vivo",
    imageArray:[phone3,phone2,phone4],
    id:"158733",
},
{
    cashback:"12% Cashback",
    phoneName: "One Plus balck body with 64GB",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Oneplus",
    imageArray:[phone4,phone3,phone2],
    id:"153223",
},
{
    cashback:"12% Cashback",
    phoneName: "Samsung Galaxy S10 Plus",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Samsung",
    imageArray:[phone2,phone3,phone4],
    id:"153003",
},
{
    cashback:"12% Cashback",
    phoneName: "Iphone 15 256 GB Pink color",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Iphone",
    imageArray:[phone2,phone3,phone4],
    id:"153053",
},
{
    cashback:"12% Cashback",
    phoneName: "Vivo 12 with 32 px front camera",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Vivo",
    imageArray:[phone3,phone2,phone4],
    id:"153311",
},
{
    cashback:"12% Cashback",
    phoneName: "One Plus balck body with 64GB",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Oneplus",
    imageArray:[phone4,phone3,phone2],
    id:"1123533",
},
{
    cashback:"12% Cashback",
    phoneName: "Samsung Galaxy S10 Plus",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Samsung",
    imageArray:[phone2,phone3,phone4],
    id:"135533",
},
{
    cashback:"12% Cashback",
    phoneName: "Iphone 15 256 GB Pink color",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Iphone",
    imageArray:[phone2,phone3,phone4],
    id:"15353",
},
{
    cashback:"12% Cashback",
    phoneName: "Vivo 12 with 32 px front camera",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Vivo",
    imageArray:[phone3,phone2,phone4],
    id:"15336",
},
{
    cashback:"12% Cashback",
    phoneName: "One Plus balck body with 64GB",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Oneplus",
    imageArray:[phone4,phone3,phone2],
    id:"153365",
},
{
    cashback:"12% Cashback",
    phoneName: "Samsung Galaxy S10 Plus",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Samsung",
    imageArray:[phone2,phone3,phone4],
    id:"153388",
},
{
    cashback:"12% Cashback",
    phoneName: "Iphone 15 256 GB Pink color",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Iphone",
    imageArray:[phone2,phone3,phone4],
    id:"1533852",
},
{
    cashback:"12% Cashback",
    phoneName: "Vivo 12 with 32 px front camera",
    currentPrice:"Rs.25,354",
    discountPrice:"Rs.29,9999",
    discount:"16% off",
    phoneEmi:"EMI starts @ Rs1356",
    availableColors: ["red", "blue", "golden", "green"],
    keyFeatures: [
        "Capacity 6 kg :Suitable for bachelors & couples",
        "Warranty: 4 years on product, 4 years on motor 800 rpm:",
        "Higher the spin speed, faster the drying time",
    ],
    brand: "Vivo",
    imageArray:[phone3,phone2,phone4],
    id:"1544433",
},
]